spring.application.name=Gym App

spring.datasource.url=jdbc:postgresql://localhost:5432/gym
spring.datasource.username=postgres
spring.datasource.password=9092
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8090
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
